// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdlgrbqayqovfqotvfjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkbGdyYnFheXFvdmZxb3R2ZmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMzMxNzgsImV4cCI6MjA1MjkwOTE3OH0.CDxQd1BD0sCRpZhiLvTXao1_-6_5PrKCck8zbi7tr5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);